// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TourGuide.Persistance.Context;

#nullable disable

namespace Persistance.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240916064754_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Shoes",
                            CreatedDate = new DateTime(2023, 11, 21, 4, 37, 20, 930, DateTimeKind.Local).AddTicks(1237),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Grocery",
                            CreatedDate = new DateTime(2024, 1, 10, 18, 38, 19, 698, DateTimeKind.Local).AddTicks(6705),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Games",
                            CreatedDate = new DateTime(2023, 3, 10, 0, 8, 28, 51, DateTimeKind.Local).AddTicks(9869),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Industrial",
                            CreatedDate = new DateTime(2023, 1, 4, 14, 18, 6, 860, DateTimeKind.Local).AddTicks(8848),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Games",
                            CreatedDate = new DateTime(2024, 2, 18, 12, 21, 55, 760, DateTimeKind.Local).AddTicks(1283),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Domain.Entities.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("OpeningTime")
                        .HasColumnType("time");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            ClosingTime = new TimeSpan(0, 17, 0, 0, 0),
                            CreatedDate = new DateTime(2024, 9, 16, 9, 47, 54, 301, DateTimeKind.Local).AddTicks(4622),
                            Description = "Ab alias ipsam et facere rem repellat veniam est ut. Cupiditate voluptatum rem ab sunt voluptate sed. Ut illum est voluptas quasi ea perferendis.",
                            ImageUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/130.jpg",
                            IsDeleted = false,
                            Latitude = -3.7446999999999999,
                            Location = "275 Shany Wells, Westborough, Latvia",
                            Longitude = -20.7972,
                            Name = "Kaiachester",
                            OpeningTime = new TimeSpan(0, 9, 0, 0, 0),
                            TicketPrice = 66.95m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            ClosingTime = new TimeSpan(0, 19, 0, 0, 0),
                            CreatedDate = new DateTime(2024, 9, 16, 9, 47, 54, 301, DateTimeKind.Local).AddTicks(6564),
                            Description = "Ut ut nisi dolores hic sed in quasi facere id. Et quam nihil vel non dolorem ex blanditiis aut. Autem aut consequatur. Vel voluptates ullam in. Debitis non nihil quos rerum ut repellendus. Quas impedit odit animi.",
                            ImageUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/449.jpg",
                            IsDeleted = false,
                            Latitude = 69.469300000000004,
                            Location = "206 Hammes Overpass, North Ronville, Latvia",
                            Longitude = 83.000200000000007,
                            Name = "Lake Lennieside",
                            OpeningTime = new TimeSpan(0, 8, 0, 0, 0),
                            TicketPrice = 84.92m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            ClosingTime = new TimeSpan(0, 17, 0, 0, 0),
                            CreatedDate = new DateTime(2024, 9, 16, 9, 47, 54, 301, DateTimeKind.Local).AddTicks(7017),
                            Description = "Quidem dolorem est esse et. Odio est corrupti. Ut eum veritatis. Aut quia voluptates repudiandae inventore minus. Velit architecto quia ut non.",
                            ImageUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/94.jpg",
                            IsDeleted = false,
                            Latitude = -2.0114999999999998,
                            Location = "23417 Hilpert Run, Runolfsdottirmouth, Central African Republic",
                            Longitude = -171.75899999999999,
                            Name = "Altenwerthville",
                            OpeningTime = new TimeSpan(0, 10, 0, 0, 0),
                            TicketPrice = 61.23m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            ClosingTime = new TimeSpan(0, 18, 0, 0, 0),
                            CreatedDate = new DateTime(2024, 9, 16, 9, 47, 54, 301, DateTimeKind.Local).AddTicks(7240),
                            Description = "Totam similique quis. Reprehenderit et doloremque. Labore molestiae necessitatibus maxime et ad et et.",
                            ImageUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/36.jpg",
                            IsDeleted = false,
                            Latitude = 22.472899999999999,
                            Location = "70035 Richard Spring, South Maribelburgh, Isle of Man",
                            Longitude = -69.720600000000005,
                            Name = "New Nelsonview",
                            OpeningTime = new TimeSpan(0, 10, 0, 0, 0),
                            TicketPrice = 63.91m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            ClosingTime = new TimeSpan(0, 18, 0, 0, 0),
                            CreatedDate = new DateTime(2024, 9, 16, 9, 47, 54, 301, DateTimeKind.Local).AddTicks(7425),
                            Description = "Quis ipsa hic quisquam rem cumque sint. Cumque atque voluptatem et distinctio eum aliquid quisquam. Tempore dolorum iure.",
                            ImageUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/356.jpg",
                            IsDeleted = false,
                            Latitude = -24.3414,
                            Location = "81726 Strosin Manor, McClurechester, Bangladesh",
                            Longitude = -10.191599999999999,
                            Name = "Ornhaven",
                            OpeningTime = new TimeSpan(0, 9, 0, 0, 0),
                            TicketPrice = 66.24m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            ClosingTime = new TimeSpan(0, 17, 0, 0, 0),
                            CreatedDate = new DateTime(2024, 9, 16, 9, 47, 54, 301, DateTimeKind.Local).AddTicks(7605),
                            Description = "Similique voluptatum ex ut assumenda. Aspernatur fugit soluta aliquam molestias et perferendis voluptatem. Ut est tempora quia aut est. Ratione est molestiae eos voluptas fugiat repudiandae praesentium maxime.",
                            ImageUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/56.jpg",
                            IsDeleted = false,
                            Latitude = 23.263200000000001,
                            Location = "57714 Armstrong Harbors, Ralphport, Western Sahara",
                            Longitude = 178.4528,
                            Name = "South Monserrateberg",
                            OpeningTime = new TimeSpan(0, 8, 0, 0, 0),
                            TicketPrice = 39.71m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            ClosingTime = new TimeSpan(0, 17, 0, 0, 0),
                            CreatedDate = new DateTime(2024, 9, 16, 9, 47, 54, 301, DateTimeKind.Local).AddTicks(7834),
                            Description = "Dolore exercitationem repellendus ipsam repudiandae quia. Repudiandae hic sed quo repudiandae voluptate tenetur. Sint corporis voluptates porro aspernatur eum voluptas. Enim velit autem dolores non tempora nisi tempora iste.",
                            ImageUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/332.jpg",
                            IsDeleted = false,
                            Latitude = -10.3308,
                            Location = "8687 Will View, Borerbury, Japan",
                            Longitude = 171.57679999999999,
                            Name = "Lake Lucieshire",
                            OpeningTime = new TimeSpan(0, 10, 0, 0, 0),
                            TicketPrice = 70.14m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            ClosingTime = new TimeSpan(0, 17, 0, 0, 0),
                            CreatedDate = new DateTime(2024, 9, 16, 9, 47, 54, 301, DateTimeKind.Local).AddTicks(8046),
                            Description = "Laborum in consequatur minima corrupti eum tempore beatae. Accusamus totam repellendus ea debitis aut. Voluptas quia aut maiores. Quia error illum necessitatibus quas labore vero.",
                            ImageUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/594.jpg",
                            IsDeleted = false,
                            Latitude = 32.528700000000001,
                            Location = "36671 Wehner Junctions, Aidenside, American Samoa",
                            Longitude = 132.70820000000001,
                            Name = "Kuhlmanbury",
                            OpeningTime = new TimeSpan(0, 8, 0, 0, 0),
                            TicketPrice = 29.01m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            ClosingTime = new TimeSpan(0, 19, 0, 0, 0),
                            CreatedDate = new DateTime(2024, 9, 16, 9, 47, 54, 301, DateTimeKind.Local).AddTicks(8235),
                            Description = "Voluptatibus eos delectus eum est. Quasi vel quia nemo ea libero ipsam. Ut maiores accusamus consequatur. Quos perspiciatis quo doloremque.",
                            ImageUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/572.jpg",
                            IsDeleted = false,
                            Latitude = 38.0002,
                            Location = "0961 Preston Dam, Port Suzanne, Japan",
                            Longitude = -17.027999999999999,
                            Name = "Ziemannshire",
                            OpeningTime = new TimeSpan(0, 8, 0, 0, 0),
                            TicketPrice = 69.69m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            ClosingTime = new TimeSpan(0, 19, 0, 0, 0),
                            CreatedDate = new DateTime(2024, 9, 16, 9, 47, 54, 301, DateTimeKind.Local).AddTicks(8416),
                            Description = "Eius omnis sit rerum rem est. Est dolores iusto architecto et nulla sapiente est illum accusamus. Alias sed laudantium error consequatur molestiae tempore eaque. Laboriosam sed nisi ea earum suscipit. Provident odit officia rerum est soluta eaque. Est adipisci eius accusantium sit accusamus nihil ipsum.",
                            ImageUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/515.jpg",
                            IsDeleted = false,
                            Latitude = -39.239199999999997,
                            Location = "982 Vincenzo Stream, Port Theodoreview, Lesotho",
                            Longitude = -92.275700000000001,
                            Name = "Marquisemouth",
                            OpeningTime = new TimeSpan(0, 8, 0, 0, 0),
                            TicketPrice = 28.67m
                        });
                });

            modelBuilder.Entity("Domain.Entities.Destination", b =>
                {
                    b.HasOne("Domain.Entities.Category", "Category")
                        .WithMany("Destinations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("Destinations");
                });
#pragma warning restore 612, 618
        }
    }
}
